version: '3.7'

networks:
  test:
    external: true

services:
  arango:
    image: brendanwheble/arango-test-data:1.0.0
    networks:
      - test
    environment:
      - ARANGO_NO_AUTH=1
    ports:
      - "8529:8529"

