version: '3.7'

services:

  basic:
    image: basic
    environment:
      - ARANGO_HOSTS=http://arango:8529
    networks:
      - test
    ports:
      - "3000:3000"
    deploy:
      replicas: 1
      update_config:
        parallelism: 5
        delay: 10s
      restart_policy:
        condition: on-failure
    command: node -r esm ./index.js

networks:
  test:
    external: true